### ISSUE TITLE
Where did you get this formula for subsampling?

### ISSUE THREAD

**Issue by eugeneyan** [Andras7/word2vec-pytorch#2]
Thanks for sharing your implementation of Word2Vec! 

One question, where did you get this formula for the implementation of subsampling? I don't seem to see it in the paper or the C-code. https://github.com/Andras7/word2vec-pytorch/blob/5281d154ed9f44293e98832a0f6b67bcfb52278c/data_reader.py#L55

**Comment by Andras7** [comment]
Hi, it comes from fastText c-code.

> void Dictionary::initTableDiscard() {
  pdiscard_.resize(size_);
  for (size_t i = 0; i < size_; i++) {
    real f = real(words_[i].count) / real(ntokens_);
    pdiscard_[i] = std::sqrt(args_->t / f) + args_->t / f;
  }
}

**Comment by eugeneyan** [comment]
Thank you for clarifying this!
